"""add_api_v2_tasks_table

Revision ID: 709895bdd124
Revises: 1af9b942657b
Create Date: 2025-08-22 00:21:29.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from open_webui.internal.db import JSONField

# revision identifiers, used by Alembic.
revision: str = "709895bdd124"
down_revision: Union[str, None] = "1af9b942657b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_v2_tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("result", JSONField, nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.BigInteger(), nullable=True),
        sa.Column("completed_at", sa.BigInteger(), nullable=True),
        sa.Column("processing_time", sa.BigInteger(), nullable=True),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.Column("request_data", JSONField, nullable=True),
        sa.Column("progress", sa.String(), nullable=True),
        sa.Column("memory_usage", JSONField, nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_v2_tasks")
    # ### end Alembic commands ###